version: "3.7"
services:
  database-mongodb-cat:
    image: mongo
    container_name: "mongodbcontainercat"
    ports:
      - 27017:27017
    restart: always
  api-adopter:
    build: .
    restart: always
    container_name: "apicatcontainer"
    ports:
      - 8082:8082
    working_dir: /opt/app
    depends_on:
      - database-mongodb-cat